-- Schema de base de datos SQLite para Sistema POS Farmacias MS
-- Versión: 1.0.0 - Multi-sucursal con sincronización Supabase

-- Información de la sucursal (configuración local única)
CREATE TABLE IF NOT EXISTS SUCURSAL (
    SUCURSAL_ID VARCHAR(36) PRIMARY KEY,
    NOMBRE_SUCURSAL VARCHAR(255) NOT NULL,
    RAZON_SOCIAL VARCHAR(255) NOT NULL,
    DIRECCION TEXT,
    TELEFONO VARCHAR(20),
    RFC VARCHAR(13),
    LOGO_PATH VARCHAR(500),
    PROPIETARIO_ID VARCHAR(36) NOT NULL,
    CONFIGURACION TEXT, -- JSON con configuración específica
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    ACTIVA BOOLEAN DEFAULT 1
);

-- Laboratorios
CREATE TABLE IF NOT EXISTS LABORATORIO (
    id_laboratorio INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre_laboratorio VARCHAR(255) NOT NULL,
    contacto_laboratorio VARCHAR(255),
    fecha_creacion DATETIME DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion DATETIME DEFAULT CURRENT_TIMESTAMP,
    sincronizado BOOLEAN DEFAULT 0,
    fecha_sincronizacion DATETIME
);

-- Productos (con identificación de sucursal)
CREATE TABLE IF NOT EXISTS PRODUCTO (
    ID_PRODUCTO INTEGER PRIMARY KEY AUTOINCREMENT,
    CODIGO_PRODUCTO VARCHAR(50) NOT NULL,
    NOMBRE_PRODUCTO VARCHAR(255) NOT NULL,
    SUSTANCIA_PRODUCTO VARCHAR(255),
    CANTIDAD_PRODUCTO DECIMAL(10,2) DEFAULT 0,
    PRECIO_PRODUCTO DECIMAL(10,2) NOT NULL,
    COSTO_PRODUCTO DECIMAL(10,2),
    ID_LABORATORIO INTEGER,
    MAX_PRODUCTO INTEGER,
    MIN_PRODUCTO INTEGER,
    IVA_PRODUCTO BOOLEAN DEFAULT 0,
    SUCURSAL_ID VARCHAR(36) NOT NULL,
    FECHA_CADUCIDAD DATE,
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    ACTIVO BOOLEAN DEFAULT 1,
    SINCRONIZADO BOOLEAN DEFAULT 0,
    FECHA_SINCRONIZACION DATETIME,
    FOREIGN KEY (ID_LABORATORIO) REFERENCES LABORATORIO(id_laboratorio),
    FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSAL(SUCURSAL_ID)
);

-- Tipos de usuario
CREATE TABLE IF NOT EXISTS TIPOUSUARIO (
    ID_TIPOUSUARIO INTEGER PRIMARY KEY,
    NOMBRE_TIPO VARCHAR(50) NOT NULL,
    PERMISOS TEXT, -- JSON array con permisos
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Usuarios (vinculados a sucursal)
CREATE TABLE IF NOT EXISTS USUARIO (
    ID_USUARIO INTEGER PRIMARY KEY AUTOINCREMENT,
    LOGIN_USUARIO VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD_USUARIO VARCHAR(255) NOT NULL, -- Hash bcrypt
    NOMBRE_USUARIO VARCHAR(100) NOT NULL,
    ID_TIPOUSUARIO INTEGER NOT NULL,
    SUCURSAL_ID VARCHAR(36) NOT NULL,
    ACTIVO BOOLEAN DEFAULT 1,
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    ULTIMO_LOGIN DATETIME,
    SINCRONIZADO BOOLEAN DEFAULT 0,
    FECHA_SINCRONIZACION DATETIME,
    FOREIGN KEY (ID_TIPOUSUARIO) REFERENCES TIPOUSUARIO(ID_TIPOUSUARIO),
    FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSAL(SUCURSAL_ID)
);

-- Salidas (Ventas) con información de pago detallada
CREATE TABLE IF NOT EXISTS SALIDA (
    ID_SALIDA INTEGER PRIMARY KEY AUTOINCREMENT,
    FOLIO_SALIDA VARCHAR(20) UNIQUE NOT NULL,
    FECHA_SALIDA DATETIME DEFAULT CURRENT_TIMESTAMP,
    TOTAL_SALIDA DECIMAL(10,2) NOT NULL,
    SUBTOTAL_SALIDA DECIMAL(10,2) NOT NULL,
    IVA_SALIDA DECIMAL(10,2) DEFAULT 0,
    TIPO_PAGO VARCHAR(10) NOT NULL CHECK (TIPO_PAGO IN ('EFECTIVO', 'TARJETA', 'MIXTO')),
    MONTO_EFECTIVO DECIMAL(10,2) DEFAULT 0,
    MONTO_TARJETA DECIMAL(10,2) DEFAULT 0,
    DATOS_TARJETA TEXT, -- JSON con información de tarjeta
    ID_USUARIO INTEGER NOT NULL,
    SUCURSAL_ID VARCHAR(36) NOT NULL,
    CANCELADA BOOLEAN DEFAULT 0,
    FECHA_CANCELACION DATETIME,
    MOTIVO_CANCELACION TEXT,
    SINCRONIZADO BOOLEAN DEFAULT 0,
    FECHA_SINCRONIZACION DATETIME,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSAL(SUCURSAL_ID)
);

-- Detalle de salidas
CREATE TABLE IF NOT EXISTS MOVSALIDA (
    ID_MOVSALIDA INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_SALIDA INTEGER NOT NULL,
    ID_PRODUCTO INTEGER NOT NULL,
    CANTIDAD_SALIDA DECIMAL(10,2) NOT NULL,
    PRECIO_UNITARIO DECIMAL(10,2) NOT NULL,
    SUBTOTAL DECIMAL(10,2) NOT NULL,
    DESCUENTO DECIMAL(10,2) DEFAULT 0,
    FECHA_CADUCIDAD DATE,
    FOREIGN KEY (ID_SALIDA) REFERENCES SALIDA(ID_SALIDA),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);

-- Entradas (Compras/Inventario)
CREATE TABLE IF NOT EXISTS ENTRADA (
    ID_ENTRADA INTEGER PRIMARY KEY AUTOINCREMENT,
    FOLIO_ENTRADA VARCHAR(20) UNIQUE NOT NULL,
    FECHA_ENTRADA DATETIME DEFAULT CURRENT_TIMESTAMP,
    TOTAL_ENTRADA DECIMAL(10,2) NOT NULL,
    PROVEEDOR VARCHAR(255),
    FACTURA VARCHAR(50),
    ID_USUARIO INTEGER NOT NULL,
    SUCURSAL_ID VARCHAR(36) NOT NULL,
    OBSERVACIONES TEXT,
    SINCRONIZADO BOOLEAN DEFAULT 0,
    FECHA_SINCRONIZACION DATETIME,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSAL(SUCURSAL_ID)
);

-- Detalle de entradas
CREATE TABLE IF NOT EXISTS MOVENTRADA (
    ID_MOVENTRADA INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_ENTRADA INTEGER NOT NULL,
    ID_PRODUCTO INTEGER NOT NULL,
    CANTIDAD_ENTRADA DECIMAL(10,2) NOT NULL,
    COSTO_UNITARIO DECIMAL(10,2) NOT NULL,
    SUBTOTAL DECIMAL(10,2) NOT NULL,
    FECHA_CADUCIDAD DATE,
    LOTE VARCHAR(50),
    FOREIGN KEY (ID_ENTRADA) REFERENCES ENTRADA(ID_ENTRADA),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);

-- Cortes de caja
CREATE TABLE IF NOT EXISTS CORTE (
    ID_CORTE INTEGER PRIMARY KEY AUTOINCREMENT,
    FECHA_CORTE DATETIME DEFAULT CURRENT_TIMESTAMP,
    TIPO_CORTE VARCHAR(10) NOT NULL CHECK (TIPO_CORTE IN ('PARCIAL', 'FINAL')),
    FOLIOS_VENDIDOS INTEGER DEFAULT 0,
    TOTAL_EFECTIVO DECIMAL(10,2) DEFAULT 0,
    TOTAL_TARJETA DECIMAL(10,2) DEFAULT 0,
    TOTAL_VENTAS DECIMAL(10,2) DEFAULT 0,
    NOTAS_CANCELADAS DECIMAL(10,2) DEFAULT 0,
    ENTRADAS_CAJA DECIMAL(10,2) DEFAULT 0,
    SALIDAS_CAJA DECIMAL(10,2) DEFAULT 0,
    ID_USUARIO INTEGER NOT NULL,
    SUCURSAL_ID VARCHAR(36) NOT NULL,
    OBSERVACIONES TEXT,
    SINCRONIZADO BOOLEAN DEFAULT 0,
    FECHA_SINCRONIZACION DATETIME,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSAL(SUCURSAL_ID)
);

-- Configuración de sincronización
CREATE TABLE IF NOT EXISTS CONFIGURACION_SINCRONIZACION (
    ID_CONFIG INTEGER PRIMARY KEY,
    SUPABASE_URL VARCHAR(500),
    SUPABASE_ANON_KEY VARCHAR(500),
    SUCURSAL_ID VARCHAR(36) NOT NULL,
    SINCRONIZACION_ACTIVA BOOLEAN DEFAULT 0,
    INTERVALO_SINCRONIZACION INTEGER DEFAULT 30, -- minutos
    ULTIMA_SINCRONIZACION DATETIME,
    FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSAL(SUCURSAL_ID)
);

-- Log de sincronización
CREATE TABLE IF NOT EXISTS SYNC_LOG (
    ID_SYNC INTEGER PRIMARY KEY AUTOINCREMENT,
    FECHA_INICIO DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_FIN DATETIME,
    TIPO_SYNC VARCHAR(15) NOT NULL CHECK (TIPO_SYNC IN ('COMPLETA', 'INCREMENTAL', 'MANUAL')),
    ESTADO VARCHAR(15) NOT NULL CHECK (ESTADO IN ('INICIADA', 'EXITOSA', 'ERROR', 'CANCELADA')),
    REGISTROS_ENVIADOS INTEGER DEFAULT 0,
    REGISTROS_RECIBIDOS INTEGER DEFAULT 0,
    MENSAJE_ERROR TEXT,
    SUCURSAL_ID VARCHAR(36) NOT NULL,
    FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSAL(SUCURSAL_ID)
);

-- PLM - Base de datos de medicamentos
CREATE TABLE IF NOT EXISTS PLM_MEDICAMENTOS (
    ID_PLM INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    SUSTANCIAS TEXT,
    FORMULACION TEXT,
    INDICACIONES TEXT,
    FARMACOCINETICA TEXT,
    LABORATORIO VARCHAR(255),
    CODIGO_BARRAS VARCHAR(50),
    FECHA_ACTUALIZACION DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Log de auditoría
CREATE TABLE IF NOT EXISTS AUDIT_LOG (
    ID_AUDIT INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER,
    ACTION_TYPE VARCHAR(50) NOT NULL,
    TABLE_NAME VARCHAR(50),
    RECORD_ID INTEGER,
    OLD_VALUE TEXT, -- JSON
    NEW_VALUE TEXT, -- JSON
    IP_ADDRESS VARCHAR(45),
    TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP,
    SUCURSAL_ID VARCHAR(36),
    FOREIGN KEY (USER_ID) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSAL(SUCURSAL_ID)
);

-- Índices para optimización de consultas
CREATE INDEX IF NOT EXISTS idx_producto_codigo ON PRODUCTO(CODIGO_PRODUCTO);
CREATE INDEX IF NOT EXISTS idx_producto_nombre ON PRODUCTO(NOMBRE_PRODUCTO);
CREATE INDEX IF NOT EXISTS idx_producto_sustancia ON PRODUCTO(SUSTANCIA_PRODUCTO);
CREATE INDEX IF NOT EXISTS idx_producto_sucursal ON PRODUCTO(SUCURSAL_ID);
CREATE INDEX IF NOT EXISTS idx_salida_fecha ON SALIDA(FECHA_SALIDA);
CREATE INDEX IF NOT EXISTS idx_salida_folio ON SALIDA(FOLIO_SALIDA);
CREATE INDEX IF NOT EXISTS idx_salida_sucursal ON SALIDA(SUCURSAL_ID);
CREATE INDEX IF NOT EXISTS idx_usuario_login ON USUARIO(LOGIN_USUARIO);
CREATE INDEX IF NOT EXISTS idx_sincronizado_productos ON PRODUCTO(SINCRONIZADO);
CREATE INDEX IF NOT EXISTS idx_sincronizado_salidas ON SALIDA(SINCRONIZADO);

-- Triggers para actualizar fecha_modificacion
CREATE TRIGGER IF NOT EXISTS update_producto_timestamp 
    AFTER UPDATE ON PRODUCTO
    BEGIN
        UPDATE PRODUCTO SET FECHA_MODIFICACION = CURRENT_TIMESTAMP WHERE ID_PRODUCTO = NEW.ID_PRODUCTO;
    END;

CREATE TRIGGER IF NOT EXISTS update_laboratorio_timestamp 
    AFTER UPDATE ON LABORATORIO
    BEGIN
        UPDATE LABORATORIO SET fecha_modificacion = CURRENT_TIMESTAMP WHERE id_laboratorio = NEW.id_laboratorio;
    END;